#ifndef BASE_STAT_CONSTS_H
#define BASE_STAT_CONSTS_H

const Character_Base_Stats TEMPEST_SHADOW_BASE_STATS{58, 25, 42, 29, 5, 2, 5, TEMPEST_SPIRIT_GROWTH, TEMPEST_STAMINA_GROWTH, TEMPEST_STRENGTH_GROWTH, TEMPEST_INTELLECT_GROWTH};
const Character_Base_Stats NIGHTWISH_BASE_STATS{80, 28, 35, 33, 3, 6, 4, NIGHTWISH_SPIRIT_GROWTH, NIGHTWISH_STAMINA_GROWTH, NIGHTWISH_STRENGTH_GROWTH, NIGHTWISH_INTELLECT_GROWTH};
const Character_Base_Stats GALLUS_BASE_STATS{46, 20, 31, 25, 2, 1, 8, GALLUS_SPIRIT_GROWTH, GALLUS_STAMINA_GROWTH, GALLUS_STRENGTH_GROWTH, GALLUS_INTELLECT_GROWTH};

#endif