#ifndef BATTLE_CONSTS_H
#define BATTLE_CONSTS_H

const long BATTLE_TRANSITION_FRAMES{120};
const long BATTLE_TRANSITION_SPEED{2};

const vector<long> BATTLE_ARROW_ICON_ANIM{1, 2, 3, 0};

const long BATTLE_ARROW_ICON_ANIMATION_SPEED{8};
const long BATTLE_ARROW_ICON_WIDTH{13};

const long BATTLE_ALLY_1_POSITION_X{100};
const long BATTLE_ALLY_1_POSITION_Y{40};
const long BATTLE_ALLY_2_POSITION_X{100};
const long BATTLE_ALLY_2_POSITION_Y{80};
const long BATTLE_ALLY_3_POSITION_X{100};
const long BATTLE_ALLY_3_POSITION_Y{120};
const long BATTLE_ALLY_4_POSITION_X{100};
const long BATTLE_ALLY_4_POSITION_Y{40};
const long BATTLE_ALLY_5_POSITION_X{100};
const long BATTLE_ALLY_5_POSITION_Y{80};
const long BATTLE_ALLY_6_POSITION_X{100};
const long BATTLE_ALLY_6_POSITION_Y{120};
const long BATTLE_ENEMY_1_POSITION_X{SCREEN_WIDTH - 150};
const long BATTLE_ENEMY_1_POSITION_Y{50};
const long BATTLE_ENEMY_2_POSITION_X{SCREEN_WIDTH - 150};
const long BATTLE_ENEMY_2_POSITION_Y{100};
const long BATTLE_ENEMY_3_POSITION_X{SCREEN_WIDTH - 150};
const long BATTLE_ENEMY_3_POSITION_Y{150};
const long BATTLE_ENEMY_4_POSITION_X{SCREEN_WIDTH - 100};
const long BATTLE_ENEMY_4_POSITION_Y{50};
const long BATTLE_ENEMY_5_POSITION_X{SCREEN_WIDTH - 100};
const long BATTLE_ENEMY_5_POSITION_Y{100};
const long BATTLE_ENEMY_6_POSITION_X{SCREEN_WIDTH - 100};
const long BATTLE_ENEMY_6_POSITION_Y{150};

const long BATTLE_PROGRESS_BAR_LEGNTH{64};
const long NUM_BATTLE_COMMAND_CHOICES{5};
const vector<string> BATTLE_COMMAND_CHOICES{"Attack", "Magic", "Items", "Guard", "Row"};
const long BATTLE_INFO_SECTION_WIDTH{80};
const long BATTLE_ARROW_ICON_PADDING_X{HERO_WIDTH / 2 - BATTLE_ARROW_ICON_WIDTH / 2};
const long BATTLE_ARROW_ICON_PADDING_Y{-20};
const long BATTLE_ARROW_ICON_ENEMY_PADDING_Y{6};
#endif
