#ifndef PROGRESS_BAR_CONSTS
#define PROGRESS_BAR_CONSTS

const Progress_Bar_Assets HP_PROGRESS{binary_Image_progress_bar_background_png_start, reinterpret_cast<long>(&binary_Image_progress_bar_background_png_size), binary_Image_progress_bar_green_png_start, reinterpret_cast<long>(&binary_Image_progress_bar_background_png_size)};
const Progress_Bar_Assets MP_PROGRESS{binary_Image_progress_bar_background_png_start, reinterpret_cast<long>(&binary_Image_progress_bar_background_png_size), binary_Image_progress_bar_blue_png_start, reinterpret_cast<long>(&binary_Image_progress_bar_blue_png_size)};
const Progress_Bar_Assets EXP_PROGRESS{binary_Image_progress_bar_background_png_start, reinterpret_cast<long>(&binary_Image_progress_bar_background_png_size), binary_Image_progress_bar_pink_png_start, reinterpret_cast<long>(&binary_Image_progress_bar_pink_png_size)};
const Progress_Bar_Assets SOUL_BREAK_PROGRESS{binary_Image_progress_bar_background_png_start, reinterpret_cast<long>(&binary_Image_progress_bar_background_png_size), binary_Image_progress_bar_red_png_start, reinterpret_cast<long>(&binary_Image_progress_bar_red_png_size)};
const Progress_Bar_Assets SCROLL_PROGRESS{binary_Image_progress_bar_background_png_start, reinterpret_cast<long>(&binary_Image_progress_bar_background_png_size), binary_Image_progress_bar_orange_png_start, reinterpret_cast<long>(&binary_Image_progress_bar_orange_png_size)};

#endif